name: Terraform Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Verify Terraform (use pre-installed version on self-hosted runner)
      - name: Verify Terraform
        run: terraform -v

      # Step 3: Azure Login (OIDC)
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          # ClientId of the Azure Service principal created.
          client-id: '5a74446b-d55e-451c-a437-85a81e5e736e'
          # TenantId of the Azure Service principal created.
          tenant-id: 'af734fcf-6a49-4af5-8ec9-51df7466b2c5'
          # Azure subscriptionId
          subscription-id: '95a90f4b-7e15-47ba-95ab-0d52bac078e4'
          

      # Step 4: Terraform Init
      - name: Terraform Init
        working-directory: .
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        working-directory: .
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        working-directory: .
        run: terraform plan

      # Step 7: Terraform Apply (only for main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: .
        run: terraform apply -auto-approve
